server:
  port: 0

spring:
  application:
    name: document-loader
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        base-url: https://generativelanguage.googleapis.com
        embedding:
          enabled: true
          project-id:  ${GOOGLE_PROJECT_ID}
          location: ${PROJECT_LOCATION}
          api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model:  gemini-2.0-flash-lite

    vectorstore:
      qdrant:
        host: 'localhost'
        port: 6334
        initialize-schema: true
        collection-name: Documents

  cloud:
    function:
      definition: fileSupplier,documentReader,splitter,titleDeterminer,vectorStoreConsumer
  docker:
    compose:
      enabled: false


file:
  supplier:
    directory: /Users/uk45382004/Documents/sample-doc
    filename: regex=.*\.(pdf|docx|txt)