server:
  port: 8080

spring:
  application:
    name: document-loader
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
        options:
          temperature: 0.1
      chat:
        model: llama3.2:1b
        options:
          temperature: 0.7
          top-p: 0.9
          top-k: 40
          num-predict: 4096
          repeat-penalty: 1.1
    vectorstore:
      qdrant:
        host: 'localhost'
        port: 6334
        initialize-schema: true
        collection-name: DocumentsCodeBase
        vector-dimension: 768
        distance: COSINE
        

  cloud:
    function:
      definition: fileSupplier,documentReader,splitter,titleDeterminer,vectorStoreConsumer


file:
  supplier:
    directory: /Users/sagarmehendale/Documents/FizzBuzz
    extensions: java,py,js,ts,cpp,c,go,rs,kt,scala,rb,php,cs,swift,yml,yaml,xml,json,md,txt,pdf,docx,html,htm