server:
  port: 8080

spring:
  application:
    name: document-loader
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: bge-m3
      chat:
        model: llama3.1:8b
    vectorstore:
      qdrant:
        host: 'localhost'
        port: 6334
        initialize-schema: true
        collection-name: DocumentsCodeBase
        vector-dimension: 1024
        distance: COSINE
        

  cloud:
    function:
      definition: fileSupplier,documentReader,splitter,titleDeterminer,vectorStoreConsumer


file:
  supplier:
    directory: /Users/sagarmehendale/Documents/Projects/Local RAG_devd/document-loader/src/main/java/com/rag/documentloader/configuration
    extensions: java,py,js,ts,cpp,c,go,rs,kt,scala,rb,php,cs,swift,yml,yaml,xml,json,md,txt,pdf,docx,html,htm