server:
  port: 0

spring:
  application:
    name: document-loader
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
      chat:
        model: llama3.2:1b
    vectorstore:
      qdrant:
        host: 'localhost'
        port: 6334
        initialize-schema: true
        collection-name: Documents

  cloud:
    function:
      definition: fileSupplier,documentReader,splitter,titleDeterminer,vectorStoreConsumer


file:
  supplier:
    directory: /Users/devgawade/Documents/sample-doc
    filename: regex=.*\.(pdf|docx|txt)