server:
  port: 8080

spring:
  application:
    name: document-loader
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: bge-m3
      chat:
        model: llama3.1:8b
    vectorstore:
      qdrant:
        host: 'localhost'
        port: 6334
        initialize-schema: true
        collection-name: DocumentsMarathi
        vector-dimension: 1024
        distance: COSINE
        

  cloud:
    function:
      definition: fileSupplier,documentReader,splitter,titleDeterminer,vectorStoreConsumer


file:
  supplier:
    directory: /Users/sagarmehendale/Documents/Writtings
    filename: regex=.*\.(pdf|docx|txt)